# Generated by Django 3.1.13 on 2022-03-08 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=35, null=True)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('profilepicture', models.ImageField(blank=True, default='uploads/profilepictures/default.png', upload_to=users.models.getcurrentusername)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('length', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.servicecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceProfile',
            fields=[
                ('freelanceuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='freelanceprofile', serialize=False, to='auth.user', verbose_name='freelance')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profilepicture', models.ImageField(blank=True, default='uploads/profilepictures/default.png', upload_to=users.models.getcurrentusername)),
                ('followers', models.ManyToManyField(blank=True, related_name='freelancefollowers', to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.adress')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('businessuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='businessprofile', serialize=False, to='auth.user', verbose_name='business')),
                ('business_name', models.CharField(blank=True, default='Unknown', max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profilepicture', models.ImageField(blank=True, default='uploads/profilepictures/default.png', upload_to=users.models.getcurrentusername)),
                ('business_number', models.IntegerField(null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='businessfollowers', to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.adress')),
                ('working_days', models.ManyToManyField(blank=True, to='users.WorkingDays')),
            ],
        ),
    ]
