# Generated by Django 3.1.13 on 2022-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='working_days',
            field=models.ManyToManyField(blank=True, to='users.WorkingDays'),
        ),
        migrations.AlterField(
            model_name='workingdays',
            name='day',
            field=models.CharField(blank=True, choices=[('1', 'Pondelok'), ('2', 'Utorok'), ('3', 'Streda'), ('4', 'Stvrtok'), ('5', 'Piatok'), ('6', 'Sobota'), ('7', 'Nedela')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
