# Generated by Django 3.1.13 on 2022-02-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='working_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workingdays'),
        ),
        migrations.AlterField(
            model_name='freelanceprofile',
            name='working_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.workingdays'),
        ),
    ]
