# Generated by Django 3.1.13 on 2022-02-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220207_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdays',
            name='day',
            field=models.CharField(choices=[('1', 'Pondelok'), ('2', 'Utorok'), ('3', 'Streda'), ('4', 'Stvrtok'), ('5', 'Piatok'), ('6', 'Sobota'), ('7', 'Nedela')], max_length=15),
        ),
    ]
