# Generated by Django 3.1.13 on 2022-02-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220203_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='freelanceprofile',
            name='working_days',
        ),
        migrations.AddField(
            model_name='workingdays',
            name='businessuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessprofileHours', to='users.businessprofile'),
        ),
    ]
