# Generated by Django 3.1.13 on 2022-02-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220207_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdays',
            name='day_of',
            field=models.BooleanField(default=False),
        ),
    ]
