# Generated by Django 3.1.13 on 2022-02-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workingdays_day_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingdays',
            old_name='day_of',
            new_name='day_off',
        ),
    ]
