# Generated by Django 3.1.13 on 2022-02-07 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20220207_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=250, null=True)),
                ('rating', models.CharField(choices=[('1', 'Velmy spokojny'), ('2', 'Spokojny'), ('3', 'Nemam Nazor'), ('4', 'Nie Velmy Spokojny'), ('5', 'Nespokojny')], max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='length',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('1', 'Sluzba pre Muzov'), ('2', 'Sluzba pre zeny')], max_length=15)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('feedback', models.ManyToManyField(blank=True, null=True, to='users.FeedBack')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='users.SubServices'),
        ),
    ]
