# Generated by Django 3.1.13 on 2022-02-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_service_servicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdays',
            name='businessuser',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='working_days',
            field=models.ManyToManyField(blank=True, null=True, to='users.WorkingDays'),
        ),
    ]
