# Generated by Django 3.1.13 on 2022-02-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220207_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='users.Service'),
        ),
    ]
