# Generated by Django 3.1.13 on 2022-02-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220203_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='address',
        ),
    ]
