# Generated by Django 3.1.13 on 2022-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_businessprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='working_days',
            field=models.ManyToManyField(blank=True, to='users.WorkingDays'),
        ),
    ]
