# Generated by Django 3.1.13 on 2022-02-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220203_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='uploads/profilepictures/default.png', upload_to=''),
        ),
    ]
