# Generated by Django 3.1.13 on 2022-02-04 00:22

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20220204_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profilepictures/default.png', upload_to=question.models.getcurrentusername),
        ),
    ]
