# Generated by Django 3.1.13 on 2022-02-03 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_service_servicecategory'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='busines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.businessprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.service'),
        ),
    ]
