# Generated by Django 3.1.13 on 2022-02-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220203_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='busines',
            new_name='business',
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
